name: Notify Discord on GitHub Activity

on:
  push:
    branches:
      - main
      - dev
      - 'feature/**'
  pull_request:
    types: [opened, closed, reopened, merged]
  issues:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]
  fork:
  star:
  watch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          EVENT_NAME="${{ github.event_name }}"

          if [ "$EVENT_NAME" = "push" ]; then
            PAYLOAD="{\"content\": \"📢 **${{ github.actor }}** pushed to branch \`${{ github.ref_name }}\` in [${{ github.repository }}](https://github.com/${{ github.repository }}).\n\nCommit message: ${{ github.event.head_commit.message }}\nCommit URL: ${{ github.event.head_commit.url }}\"}"
          elif [ "$EVENT_NAME" = "pull_request" ]; then
            ACTION="${{ github.event.action }}"
            PR_NUMBER="${{ github.event.pull_request.number }}"
            PR_TITLE="${{ github.event.pull_request.title }}"
            PR_URL="${{ github.event.pull_request.html_url }}"
            if [ "$ACTION" = "closed" ] && [ "${{ github.event.pull_request.merged }}" = "true" ]; then
              ACTION="merged"
            fi
            PAYLOAD="{\"content\": \"🔀 Pull request #${PR_NUMBER} **${PR_TITLE}** was **${ACTION}** by **${{ github.actor }}**. <${PR_URL}>\"}"
          elif [ "$EVENT_NAME" = "issues" ]; then
            ACTION="${{ github.event.action }}"
            ISSUE_NUMBER="${{ github.event.issue.number }}"
            ISSUE_TITLE="${{ github.event.issue.title }}"
            ISSUE_URL="${{ github.event.issue.html_url }}"
            PAYLOAD="{\"content\": \"🐛 Issue #${ISSUE_NUMBER} **${ISSUE_TITLE}** was **${ACTION}** by **${{ github.actor }}**. <${ISSUE_URL}>\"}"
          elif [ "$EVENT_NAME" = "issue_comment" ]; then
            ISSUE_NUMBER="${{ github.event.issue.number }}"
            COMMENTER="${{ github.event.comment.user.login }}"
            ISSUE_URL="${{ github.event.issue.html_url }}"
            PAYLOAD="{\"content\": \"💬 New comment by **${COMMENTER}** on issue #${ISSUE_NUMBER}. <${ISSUE_URL}>\"}"
          elif [ "$EVENT_NAME" = "fork" ]; then
            PAYLOAD="{\"content\": \"🍴 Repository [${{ github.repository }}](https://github.com/${{ github.repository }}) was forked by **${{ github.actor }}**.\"}"
          elif [ "$EVENT_NAME" = "star" ]; then
            PAYLOAD="{\"content\": \"⭐ Repository [${{ github.repository }}](https://github.com/${{ github.repository }}) was starred by **${{ github.actor }}**.\"}"
          elif [ "$EVENT_NAME" = "watch" ]; then
            PAYLOAD="{\"content\": \"👁️ Repository [${{ github.repository }}](https://github.com/${{ github.repository }}) was watched by **${{ github.actor }}**.\"}"
          else
            PAYLOAD="{\"content\": \"ℹ️ Event \`${EVENT_NAME}\` received from **${{ github.actor }}**.\"}"
          fi

          curl -H "Content-Type: application/json" -X POST -d "$PAYLOAD" $DISCORD_WEBHOOK
