name: Notify Discord on Push and PR

on:
  push:
    branches:
      - main
      - dev
      - 'feature/**'
  pull_request:
    types: [opened, closed, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          EVENT="${{ github.event_name }}"
          ACTOR="${{ github.actor }}"
          REPO="${{ github.repository }}"

          if [ "$EVENT" = "push" ]; then
            REF="${{ github.ref_name }}"
            COMMIT_MSG="${{ github.event.head_commit.message }}"
            COMMIT_URL="${{ github.event.head_commit.url }}"
            MESSAGE="📦 **$ACTOR** pushed to \`$REF\` in \`$REPO\`\\nCommit: $COMMIT_MSG\\n🔗 <$COMMIT_URL>"
          
          elif [ "$EVENT" = "pull_request" ]; then
            ACTION="${{ github.event.action }}"
            PR_TITLE="${{ github.event.pull_request.title }}"
            PR_URL="${{ github.event.pull_request.html_url }}"
            MERGED="${{ github.event.pull_request.merged }}"
            if [ "$ACTION" = "closed" ] && [ "$MERGED" = "true" ]; then
              ACTION="merged"
            fi
            MESSAGE="🔀 Pull Request **$PR_TITLE** was **$ACTION** by **$ACTOR**\\n🔗 <$PR_URL>"
          fi

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"$MESSAGE\"}" \
            $DISCORD_WEBHOOK
