name: Notify Discord on Push

on:
  push:
    branches:
      - main
      - dev
      - 'feature/**'

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"📦 ${{ github.actor }} pushed to `${{ github.ref_name }}` in [${{ github.repository }}](https://github.com/${{ github.repository }}/commits).\"}" \
            $DISCORD_WEBHOOK
