name: Notify Discord on Push

on:
  push:
    branches:
      - main
      - dev
      - 'feature/**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"📦 **${{ github.actor }}** pushed to branch \`${{ github.ref_name }}\` in [${{ github.repository }}](https://github.com/${{ github.repository }}).\n\n**Commit:** ${{ github.event.head_commit.message }}\n🔗 [View Commit](${{ github.event.head_commit.url }})\"}" \
            $DISCORD_WEBHOOK
